version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: vue-press
    command: yarn docs:dev
    ports:
      - 8080:8080
    environment:
      - HOST=0.0.0.0
    volumes:
      - type: bind
        source: ./
        target: /vue-press
      - type: volume
        source: node-modules-data
        target: /vue-press/node_modules
    stdin_open: true
    tty: true

volumes:
  node-modules-data:
